<?php

//$viewModel = $block->getData(key: 'viewModel');
$viewModel = $block->getData('viewModel');

?>


<div data-bind="scope:'fahim-component'">
    <h1 data-bind="text: title"></h1>
    
    <ul data-bind="foreach: {data: getItems(), as: 'block'}">
        <li><a data-bind="text:block.title"></a>
            <p data-bind="text: block.content"></p>
        </li>
    </ul>

</div>

<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "fahim-component":{
                    "component":"Embitel_Tech/js/component",
                    "title": "<?= $viewModel->getName()?>",
                    "items": <?= $viewModel->getItemsJson(); ?>
                }
            }
        }
    }
}
</script>